config/routes.rb
AuctionApp::Application.routes.draw do

  resources :categories
  resources :items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :bids, only: [:create, :destroy]

  root 'items#index'

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/item.rb
class Item < ActiveRecord::Base
  default_scope -> { order('items.created_at DESC') }

  belongs_to :category
  belongs_to :user
  has_many   :bids, dependent: :delete_all

  validates :name,        presence: true, length: 3..50
  validates :starting_price, numericality: true
  validates :category_id, presence: true
  validates :user_id,     presence: true
  validates :close_date,  presence: true

  # Paperclip
  has_attached_file :avatar,
                    styles: { :medium => "200x200>", :thumb => "50x50>" },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :avatar, less_than: 3.megabytes

  def self.search(query, category_id)
    if category_id && !category_id.empty?
      items = where('description || name like ? and category_id = ?', "%#{query}%", category_id)
      items
    elsif query && !query.empty?
      items = where('description || name like ?', "%#{query}%")
      items
    else
      find(:all)
    end
  end

  def has_bid?
    Bid.where('item_id = ?', self.id).count > 0
  end

  def closed?
    !close_date.nil? && (Time.now >= close_date)
  end

  def won?
    closed? && has_bid?
  end

  def winner
    won? && Bid.where('item_id = ?', self.id).first.user
  end

  def self.that_user_won(user)
    result = []
    self.that_user_bid_on(user).each { |item| result.push(item) if item.bids.first.user_id == user.id }
    result
  end

  def self.that_user_bid_on(user)
    joins('JOIN bids ON bids.item_id = items.id').where(bids: { user_id: user.id }).where('items.close_date < ?', Time.now).all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :signed_in_user,    only: [               :new, :edit, :create, :update, :destroy]
  before_action :set_item,          only: [        :show,       :edit,          :update, :destroy]
  before_action :categories_array,  only: [:index,        :new, :edit, :create, :updated         ]
  before_action :correct_user,      only: [                     :edit,          :updated         ]
  before_action :correct_user_admin,only: [                                              :destroy]

  # GET /items
  # GET /items.json
  def index
    @items_page = :page
    @items = Item.paginate(page: params[@items_page], per_page: 10)
                 .where('items.close_date >= ?', Time.now)
                 .search(params[:query], params[:category_id])
    #
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @bid  = Bid.new
    @bids = Bid.paginate(page: params[:page], per_page: 5)
               .where('item_id = ?', @item.id)
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.close_date = Time.now + 1.day
  end

  # GET /items/1/edit
  def edit
    if @item.closed?
      redirect_to @item, notice: 'You can\'t edit this now. Bidding has ended.'
    elsif @item.has_bid?
      redirect_to @item, notice: 'You can\'t edit this now. Bidding has begun.'
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    if @item.close_date <= Time.now
      @item.errors.add(:close_date, 'must close after today')
      render action: 'new'
    else
      respond_to do |format|
        if @item.save
          format.html { redirect_to @item, notice: 'Item was successfully created.' }
          format.json { render action: 'show', status: :created, location: @item }
        else
          format.html { render action: 'new' }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    if @item.has_bid?
      redirect_to @item, notice: 'You can\'t edit this now. Bidding has begun.'
    else
      respond_to do |format|
        if @item.update(item_params)
          format.html { redirect_to @item, notice: 'Item was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  #
  def categories_array
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:name, :description, :user_id, :starting_price, :category_id, :close_date, :avatar)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: 'Please sign in.'
    end
  end

  def correct_user
    unless signed_in? && current_user?(@item.user)
      redirect_to items_url, alert: "You can't do that!?."
    end
  end

  def correct_user_admin
    unless signed_in? && (current_user?(@item.user) || current_user.admin?)
      redirect_to items_url, alert: "You can't do that!?."
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages', obj: f.object %>
  <table class="item_detail">
    <tbody>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <tr class="field">
        <td class="detail_label"><%= f.label :name %></td>
        <td class="detail_input"><%= f.text_field :name %></td>
      </tr>
      <tr class="field">
        <td class="detail_label"><%= f.label :description %></td>
        <td class="detail_input"><%= f.text_area :description %></td>
      </tr>
      <tr class="field">
        <td class="detail_label"><%= f.label :starting_price %></td>
        <td class="detail_input"><%= f.number_field :starting_price, {min: "0.00", max: "999999999.99", step: "0.01"} %></td>
      </tr>
      <tr class="field">
        <td class="detail_label">Category</td>
        <td class="detail_input"><%= f.select :category_id, options_for_select(@categories, selected: @item.category_id), prompt: "Select Category" %></td>
      </tr>
      <tr class="field">
        <td class="detail_label"><%= f.label :close_date, 'Close Date' %></td>
        <td class="detail_input"><%= f.date_field :close_date, placeholder: "dd/mm/yyy", min: Time.now + 1.day %></td>
      </tr>
      <tr class="field">
        <td class="detail_label"><%= f.label :avatar, 'Upload Image' %></td>
        <td class="detail_input"><%= f.file_field :avatar, title: 'upload' %></td>
      </tr>
    </tbody>
  </table>
  <div class="container_nav">
    <%= f.submit "Save", class: "bordered_link", title: "Save" %>
  </div>
<% end %>

app/views/items/_index_items.html.erb
<div id="item_list">
  <% items.each do |item| %>
    <div class="item_wrap">
      <div class="bullet"><%= image_tag item.avatar.url(:thumb) if item.avatar.file? %></div>
      <p>
        <span class="item_name">
          <%= link_to truncate(item.name, length: 50), item, title: "Show item details" %>
        </span>
        <br/>
        <span class="item_cat">
          <%= number_to_currency(highest_bid_for(item.id) || item.starting_price) %>
          (<%= link_to item.category.name, items_path(category_id: item.category_id), title: "Search for all #{item.category.name}" %>)
        </span>
      </p>
    </div>
  <% end %>
  <%= content_tag(:h3, "No items found", class: "no_items_message") if items.size == 0 %>
  <%= will_paginate items, param_name: param_name %>
</div>

app/views/items/edit.html.erb
<% @page_title = "Edit" %>

<%= render 'form' %>

<div class="container_nav">
  <%= link_to 'Cancel', @item, class: "bordered_link back_button", title: "Return to details page" %>
</div>

app/views/items/index.html.erb
<% if params[:category_id]
    @page_title = "Items for Sale | Search Results"
  else
    @page_title = "Items for Sale"
  end %>

<%= form_tag items_path, method: 'get', class: "search_form" do %>
  <p>
    <%= select_tag :category_id, options_for_select(@categories, selected: params[:category_id]), prompt: "Select Category" %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil, title: "Search item names and descriptions" %>
    <%= link_to "Clear", items_path, class: "bordered_link", title: "Clear search" if params[:category_id] %>
  </p>
<% end %>

<%= render 'index_items', items: @items, param_name: @items_page %>
<br>

<div class="container_nav">
  <%= link_to 'Something to Sell?', {action: 'new'}, class: "bordered_link", title: "Something to sell?" %>
</div>

app/views/items/new.html.erb
<% @page_title = "Want to sell something?" %>

<%= render 'form' %>

<div class="container_nav">
  <%= link_to 'Cancel', items_path, class: "bordered_link back_button", title: "Return to all items" %>
</div>

app/views/items/show.html.erb
<% @page_title = @item.name %>

<% if @item.avatar.file? %>
  <div class="item_avatar">
    <%= image_tag @item.avatar.url(:medium) %>
  </div>
<% end %>
<table class="item_detail">
  <tbody>
    <tr class="field">
      <td class="detail_label">Description</td>
      <td class="detail_value"><%= @item.description %></td>
    </tr>
    <tr class="field">
      <td class="detail_label">Seller</td>
      <td class="detail_value"><%= link_to "#{@item.user.first_name} #{@item.user.last_name}", @item.user, title: "Show account profile" %></td>
    </tr>
    <tr class="field">
      <td class="detail_label">Price</td>
      <td class="detail_input"><%= number_to_currency(highest_bid_for(@item.id) || @item.starting_price) %></td>
    </tr>
    <tr class="field">
      <td class="detail_label">Category</td>
      <td class="detail_value"><%= link_to @item.category.name, items_path(category_id: @item.category_id), title: "Search for all #{@item.category.name}" %></td>
    </tr>
    <tr class="field">
      <td class="detail_label">Created</td>
      <td class="detail_value"><%= "#{time_ago_in_words(@item.created_at)} ago" %></td>
    </tr>
    <% if @item.closed? %>
      <% if @item.won? %>
        <tr class="field">
          <td class="detail_label">Won by</td>
          <td class="detail_value">
            <%= link_to "#{@item.winner.first_name} #{@item.winner.last_name}", @item.winner %>
            <%= "#{time_ago_in_words(@item.close_date)} ago" %>
          </td>
        </tr>
      <% else %>
        <tr class="field">
          <td class="detail_label">Closed</td>
          <td class="detail_value"><%= "#{time_ago_in_words(@item.close_date)} ago" %></td>
        </tr>
      <% end %>
    <% else %>
      <tr class="field">
        <td class="detail_label">Closing</td>
        <td class="detail_value"><%= "in #{time_ago_in_words(@item.close_date)}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if signed_in? && !@item.closed? && (current_user?(@item.user) || current_user.admin?)  %>
  <div class="container_nav">
    <% if current_user?(@item.user) && !@item.has_bid? %>
      <%= link_to 'Edit', edit_item_path(@item), class: "bordered_link", title: "Edit this item" %>
    <% end %>
    <%= link_to 'Delete', @item,
                          method: :delete,
                          data: { confirm: "Are you sure you want to delete the item \"#{@item.name}\"?" },
                          class: "bordered_link",
                          title: "Delete this item" %>
  </div>
<% end %>

<% if signed_in? %>
  <%= render 'bids/index' unless @bids.count==0 %>
  <%= render 'bids/form' unless (current_user?(@item.user) || @item.closed?) %>
<% end %>

<div class="container_nav">
  <%= link_to "Sign in to Bid", signin_path, class: "bordered_link", title: "Sign in to bid" unless signed_in? %>
  <%= link_to 'See All Items',  items_path,  class: "bordered_link back_button", title: "Return to all items" %>
</div>