config/routes.rb
AuctionApp::Application.routes.draw do

  resources :categories
  resources :items
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :bids, only: [:create, :destroy]

  root 'items#index'

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Robert j Chatfield | s2187099 | <%= link_to 'Documentation', '/documentation.txt', target: '_blank' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="accountbar">
    <% if signed_in? %>
      Welcome, <%= link_to current_user.first_name, current_user %>
      <%= link_to "Sign Out", signout_path, method: 'delete', class: "bordered_link" %>
    <% else %>
      <%= link_to "Sign In", signin_path, class: "bordered_link" %>
      <%= link_to "Sign Up", signup_path, class: "bordered_link" %>
    <% end %>
  </div>
  <h1><%= link_to("Auction App", root_path) %></h1>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <h2><%= @page_title %></h2>
</header>

app/views/layouts/_nav.html.erb
<nav>
  <%= link_to "Buy", items_path, class: "bordered_link" %>
  <%= link_to "Sell", new_item_path, class: "bordered_link" %>
  <%= content_tag :div, nil, class: "separator" %>
  <% if signed_in? && current_user.admin? %>
    <%= content_tag :div, nil, class: "separator" %>
    <%= link_to "Admin", controller: "categories"%>
  <% end %>
  <% if signed_in? %>
    <%= content_tag :div, nil, class: "separator" %>
    <%= link_to "Accounts", users_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    Auction App
    <%= (" | " + @page_title) if @page_title  %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag  params[:controller], "data-turbolinks-track" => true %>
  <link href="http://fonts.googleapis.com/css?family=Raleway:400,700,500" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/nav' %>
  <section>
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>